# Generated by Django 4.2.30 on 2026-06-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vaccinationcard',
            name='rabies',
            field=models.DateField(default='2026-06-16'),
        ),
        migrations.AlterField(
            model_name='vetvisit',
            name='date',
            field=models.DateField(default='2026-06-16'),
        ),
    ]
